services:
  - type: web
    name: cinamaticket-scraper
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
      pip install -r requirements.txt
    startCommand: python scraper.py && python3 -m http.server public
    plan: free
