services:
  - type: web
    name: cinamaticket-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scraper.py && python3 -m http.server public
    plan: free
