services:
  - type: web
    name: cinamaticket-scraper
    env: python
    buildCommand: ""
    startCommand: python scraper.py && python3 -m http.server 10000
    plan: free
    envVars: []
    autoDeploy: true
    branch: main
    rootDir: .
