name: Daily Update

on:
  schedule:
    - cron: '0 6 * * *'  # هر روز ساعت ۶ صبح به‌وقت UTC (ساعت ۹:۳۰ صبح ایران)
  workflow_dispatch:      # اجرای دستی

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit updated HTML
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/now_showing.html
          git commit -m "update HTML [auto]" || echo "no changes to commit"
          git push

      - name: Upload HTML output
        uses: actions/upload-artifact@v4
        with:
          name: samfaa_output
          path: samfaa_page.html
